### PR TITLE
Customizable layout

### PR DESCRIPTION
**Pull request by akfzambrana**
Making the layout be more customizable

**Work in progress**, please don't merge it yet"

### CODE REVIEW

**Comment by akfzambrana** [comment]
@WendellAdriel please take a look how this is going and if you like the changes that I'm doing 😉

**Comment by WendellAdriel** [comment]
I saw you made some commits, is this ready to merge or may I wait some more commits @akfzambrana?

**Comment by akfzambrana** [comment]
@WendellAdriel It's ready to merge, please take a look to my changes and see if you like it

**Comment by WendellAdriel** [comment]
It's awesome @akfzambrana. Thank you very much!!! I'll merge it later because I will create a tag, write some things in the changelog file and share the new version with everyone.

**Comment by WendellAdriel** [comment]
Can you make a list of things to put in the changelog file @akfzambrana?

**Comment by akfzambrana** [comment]
Basically I made only this three big changes
- Basic adjustments for better responsiveness
- Added more variables so anyone can customize almost everything in the curriculum without have to know a lot of Sass or need to make changes in the style files.
- Fixed some layout bugs

**Comment by WendellAdriel** [comment]
Thank you very much @akfzambrana!!!! :+1: :wink:

**Review by WendellAdriel — APPROVED** [review]

**Pull request merged**
