### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by khaosdoctor**
We have to add the spaces or this won't work :D

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Strange, in my page it's working, because I made some tests when I made this change:
http://wendelladriel.github.io/

And the code is the same:
https://github.com/WendellAdriel/WendellAdriel.github.io/blob/master/_includes/footer.html#L3

Are you sure that isn't working to you? What's happening?

**Comment by khaosdoctor** [comment]
I don't know, I though this was part of the liquid templates syntax... It shows only the URL to github, without the username. Changed to this and now it's working...

**Comment by WendellAdriel** [comment]
No, I made some tests here and it's ok. I will not close this PR now, I'll wait to merge it with the next version ok @khaosdoctor? Thanks for the help!

**Comment by khaosdoctor** [comment]
Ok 👌

**Review by WendellAdriel — APPROVED** [review]

**Pull request merged**
